export const properties = [
  {
    id: "1",
    listedBy: "Jakob Calzoni",
    sellerId: "S1478536",
    category: "Furnished Apartments",
    price: "$20,000.00",
    available: "SALE",
    email: "example@gmail.com",
    phone: "+1 7768 945 630",
    zipCode: "10011",
    address: "Lorem Ipsum Is Simply Dummy...",
    active: true,
  },
  {
    id: "2",
    listedBy: "Jaxson Mango",
    sellerId: "S1478536",
    category: "Studio Apartments",
    price: "$20,000.00",
    available: "RENT",
    email: "example@gmail.com",
    phone: "+1 7768 945 630",
    zipCode: "10011",
    address: "Lorem Ipsum Is Simply Dummy...",
    active: false,
  },
  {
    id: "3",
    listedBy: "Martin Dias",
    sellerId: "S1478536",
    category: "Studio Apartments",
    price: "$20,000.00",
    available: "RENT",
    email: "example@gmail.com",
    phone: "+1 7768 945 630",
    zipCode: "10011",
    address: "Lorem Ipsum Is Simply Dummy...",
    active: false,
    sold: true,
  },
  {
    id: "4",
    listedBy: "Lincoln Calzoni",
    sellerId: "S1478536",
    category: "Unfurnished Home",
    price: "$20,000.00",
    available: "SALE",
    email: "example@gmail.com",
    phone: "+1 7768 945 630",
    zipCode: "10011",
    address: "Lorem Ipsum Is Simply Dummy...",
    active: true,
  },
  {
    id: "5",
    listedBy: "James Saris",
    sellerId: "S1478536",
    category: "Unfurnished Home",
    price: "$20,000.00",
    available: "SALE",
    email: "example@gmail.com",
    phone: "+1 7768 945 630",
    zipCode: "10011",
    address: "Lorem Ipsum Is Simply Dummy...",
    active: true,
  },
  {
    id: "6",
    listedBy: "Carla Philips",
    sellerId: "S1478536",
    category: "Studio Apartments",
    price: "$20,000.00",
    available: "RENT",
    email: "example@gmail.com",
    phone: "+1 7768 945 630",
    zipCode: "10011",
    address: "Lorem Ipsum Is Simply Dummy...",
    active: true,
  },
  {
    id: "7",
    listedBy: "Lindsey Korsgaard",
    sellerId: "S1478536",
    category: "Furnished Home",
    price: "$20,000.00",
    available: "SALE",
    email: "example@gmail.com",
    phone: "+1 7768 945 630",
    zipCode: "10011",
    address: "Lorem Ipsum Is Simply Dummy...",
    active: false,
  },
  {
    id: "8",
    listedBy: "Martin Geidt",
    sellerId: "S1478536",
    category: "Furnished Home",
    price: "$20,000.00",
    available: "RENT",
    email: "example@gmail.com",
    phone: "+1 7768 945 630",
    zipCode: "10011",
    address: "Lorem Ipsum Is Simply Dummy...",
    active: true,
  },
  {
    id: "9",
    listedBy: "Davis Levin",
    sellerId: "S1478536",
    category: "Penthouse",
    price: "$20,000.00",
    available: "RENT",
    email: "example@gmail.com",
    phone: "+1 7768 945 630",
    zipCode: "10011",
    address: "Lorem Ipsum Is Simply Dummy...",
    active: true,
  },
  {
    id: "10",
    listedBy: "Carter Vaccaro",
    sellerId: "S1478536",
    category: "Unfurnished Home",
    price: "$20,000.00",
    available: "SALE",
    email: "example@gmail.com",
    phone: "+1 7768 945 630",
    zipCode: "10011",
    address: "Lorem Ipsum Is Simply Dummy...",
    active: true,
  },
  {
    id: "11",
    listedBy: "Miracle Westervelt",
    sellerId: "S1478536",
    category: "Furnished Apartments",
    price: "$20,000.00",
    available: "SALE",
    email: "example@gmail.com",
    phone: "+1 7768 945 630",
    zipCode: "10011",
    address: "Lorem Ipsum Is Simply Dummy...",
    active: true,
  },
  {
    id: "12",
    listedBy: "Vaccaro Bator",
    sellerId: "S1478536",
    category: "Furnished Apartments",
    price: "$20,000.00",
    available: "SALE",
    email: "example@gmail.com",
    phone: "+1 7768 945 630",
    zipCode: "10011",
    address: "Lorem Ipsum Is Simply Dummy...",
    active: true,
  },
  {
    id: "13",
    listedBy: "Dulce Bator",
    sellerId: "S1478536",
    category: "Furnished Apartments",
    price: "$20,000.00",
    available: "SALE",
    email: "example@gmail.com",
    phone: "+1 7768 945 630",
    zipCode: "10011",
    address: "Lorem Ipsum Is Simply Dummy...",
    active: true,
  },
];
